AppFlowy-IO/AppFlowy-Docs

essential-documentation/install-appflowy/installation-methods/installing-with-docker.md

Related: https://github.com/AppFlowy-IO/AppFlowy/pull/373

refactor: Docker section and discourage usage of xhost (#3)

---

essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/submitting-your-first-pull-request.md

Correct a minor spelling error. Capitalised a proper noun as well.

fix: Correct Spelling

---

essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-windows.md

Remove Unnecessary steps from Environment Setup documentation on Windows.

---

essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-linux.md

I saw a lot of repetitive questions in the github issue tracker, https://github.com/AppFlowy-IO/AppFlowy/issues/112 and https://github.com/AppFlowy-IO/AppFlowy/issues/566
I thought I could remove some pain by adding this info box to the documentation.

Add issue-specific case to documentation

---

essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-windows.md

Add a few instructions to compile from a naive Windows 11 (no compiler set at all).

Compile with Windows 11

---

essential-documentation/install-appflowy/installation-methods/troubleshooting-when-installing-appflowy.md

updated troubleshooting page from github issues, discussions and discord channels. closes [issue #1096](https://github.com/AppFlowy-IO/AppFlowy/issues/1096)

updated troubleshooting page, closes #1096

---

essential-documentation/install-appflowy/installation-methods/installing-with-docker.md

The `latest` tag has not been updated for 8 months

Update docker instructions

---

essential-documentation/install-appflowy/requirements.md

Closes issue [1002](https://github.com/AppFlowy-IO/AppFlowy/issues/1002)
Added minimum system requirements!

Added Minimum System Requirements

---

essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-linux.md

Provide documentation instructions for issue https://github.com/AppFlowy-IO/AppFlowy/issues/1617

docs: added flutter version requirement tips for building on linux

---

essential-documentation/shortcuts.md

Mapped all the KeyBindings present [here](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/app_flowy/packages/appflowy_editor/lib/src/service/shortcut_event/built_in_shortcut_events.dart) to the `shortcuts.md` file, so that we can redirect the user to this page when the user wants to view all the shortcuts available.

docs(shortcuts.md): Add shortcuts

---

essential-documentation/shortcuts.md

- Fixed the alignment issue, in the selection section.

docs: align shortcuts

---

essential-documentation/contribute-to-appflowy/architecture/frontend/frontend/codemap.md

updated codemap.md file which had minor spelling corrections

minor spelling corrections

---

essential-documentation/shortcuts.md

Closes: #2496
https://github.com/AppFlowy-IO/AppFlowy/issues/2496

chore: update selection shortcuts

---

essential-documentation/contribute-to-appflowy/write-for-appflowy/drafts/draft-how-to-contribute-to-appflowy.md

Base setup for draft, not ready for review though. Tentative deadline by the 7th of May, 2023. Currently working on content, feel free to contact me for any queries on the same.

[Draft] How to contribute to AppFlowy

---

essential-documentation/contribute-to-appflowy/write-for-appflowy/drafts/draft-how-to-contribute-to-appflowy.md

fix: How to Contribute to Appflowy Draft

---

essential-documentation/install-appflowy/installation-methods/mac-windows-linux-packages/README.md

Spelling error*
Windowns -> Windows

🔧 spelling error

---

essential-documentation/contribute-to-appflowy/write-for-appflowy/drafts/draft-how-to-contribute-to-appflowy.md

* Added spacing for clarity
* Removed unecessary HTML formatting
* Ensured consistency of AppFlowy branding (i.e. case)
* Made sure heading hierarchy was consistent
* Fixed use of unordered lists
* Enforced stylistic rule for links (i.e. make links contain relevant text)
* Edited for clarity

Edits to how-to-contribute-to-appflowy draft

---

essential-documentation/contribute-to-appflowy/blog-post-work-in-progress/creating-a-calendar-view-for-the-appflowy-database.md

The document needs some work on the introduction as it does not clearly state the intent of the piece.
Also, if the goal is to provide a tutorial as to how to create a view, or at least a model to work from, I don't think there is sufficient information

Initial pass for readability and formatting

---

essential-documentation/contribute-to-appflowy/blog-post-work-in-progress/appflowy-with-supabase-wip.md

Initial pass to clean up the doc

Edits for structure and readability for Supabase Document

---

essential-documentation/contribute-to-appflowy/blog-post-work-in-progress/demystifying-appflowy-editors-codebase.md

Removed complex mixing of bullets and ordered lists in favor of headings
Removed unrecessary ordered lists
Cleaned up formatting issues especially with directory structures
More detail should be added regarding transactions, particularly what is meant by "state refresh"
The testing section of best practices is weak, probably should refer to an external document specifically on test case writing methodology
I think for long file paths, it is best to use code blocks (multiline code blocks delimited with three backticks) as these are going to tend to run off screen
There's still a lot of inconsistent formatting, especially when inline code (single backticks) are used vs. bold

Structure, formatting, and readability fixes

---

blog-highlights/demystifying-appflowy-editors-codebase.md

- Added a link to an article that already explains the State Refresh of Transaction.
- Added more content in the Testing section.
- Fixed minor formatting issues and spelling mistakes.

fix: add testing and link transaction article

---

blog-highlights/demystifying-appflowy-editors-codebase.md

The testing section is much improved
I added some external references for certain terms
There are some inline TODO: comments for additional issues to address

Reviewed the testing section, added some inline TODOs

---

appflowy/readme/install-appflowy.md

Extremely minor typo fix

---

documentation/appflowy/draft-how-to-contribute-to-appflowy.md

Broken Link Fixed
Issue was created on main repository of appflowy : [Issue 4010](https://github.com/AppFlowy-IO/AppFlowy/issues/4010)
Kindly close the issue linking this pull request

Fixed Broken Link in Docs

---

guides/appflowy/README.md

Update urls to the correct path

Update urls to the correct path

---

appflowy/community/get-in-contact.md

Updated discord link, as mentioned in the discord. Old one was expired, new one should not expire or reach an invite limit.
Thanks.

Updated discord link

---

documentation/appflowy/from-source/environment-setup/README.md
documentation/appflowy/from-source/environment-setup/building-on-linux.md
documentation/appflowy/from-source/environment-setup/building-on-windows.md

- update Flutter version to 3.22.3
- update Rust version to 1.80.1

chore: update flutter setup doc

---

README.md

replaced the word alternation to alternative to improve readability.

docs: a tiny word fix to improve readability.

---

documentation/appflowy-cloud/openapi/.openapi-generator/FILES
documentation/appflowy-cloud/openapi/Apis/OAuthApi.md
documentation/appflowy-cloud/openapi/Models/gotrue_token_response.md
documentation/appflowy-cloud/openapi/README.md
documentation/appflowy-cloud/openapi/components/gotrue_token_response.yaml
documentation/appflowy-cloud/openapi/openapi.yaml
documentation/appflowy-cloud/openapi/paths/oauth_redirect_token.yaml

feat: add oauth redirect token api

---

documentation/appflowy/from-source/environment-setup/building-on-macos.md

- fix git clone url
- fix path

chore: fix typo in building on macos

---

documentation/appflowy/from-source/environment-setup/README.md
documentation/appflowy/from-source/environment-setup/building-on-linux.md
documentation/appflowy/from-source/environment-setup/building-on-windows.md

AppFlowy flutter requirement has been increased to 3.27.4.

fix: update flutter version for doc

---

documentation/appflowy-cloud/openapi/.openapi-generator/FILES
documentation/appflowy-cloud/openapi/Apis/OAuthApi.md
documentation/appflowy-cloud/openapi/Apis/WorkspacesApi.md
documentation/appflowy-cloud/openapi/Models/folder_view.md
documentation/appflowy-cloud/openapi/Models/getWorkspaceFolder_200_response.md
documentation/appflowy-cloud/openapi/Models/gotrueToken_request.md
documentation/appflowy-cloud/openapi/Models/gotrue_token_response.md
documentation/appflowy-cloud/openapi/README.md
documentation/appflowy-cloud/openapi/components/folder_view.yaml
documentation/appflowy-cloud/openapi/components/gotrue_token_response.yaml
documentation/appflowy-cloud/openapi/openapi.yaml
documentation/appflowy-cloud/openapi/paths/gotrue_token.yaml
documentation/appflowy-cloud/openapi/paths/workspace_folder.yaml

OpenAPI doc for retrieving workspace folder

Api doc for get workspace folder
